version: '3'

services:

  mysql_db:
    container_name: trivia_db
    image: mysql:5.7
    restart: always
    ports:
     - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  back:
    container_name: trivia_back
    build: ./back-end
    restart: always
    ports:
     - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      HOSTNAME: trivia_db
    depends_on:
      - mysql_db

  front:
    container_name: trivia_front
    build: ./front-end
    restart: always
    tty: true
    ports:
     - 3000:3000
    depends_on:
      - back