version: '3'

services:
  node:
    build: .
    volumes: 
      - ./:/app
    container_name: trivia-back
    tty: true
    stdin_open: true
    command: /bin/sh
    restart: always
    ports:
      - 3001:3001
    environment:
      - PORT=3001
